// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MovieDBconnection.PersonDiscoveryJsonTypes;

namespace MovieDBconnection
{

    internal class PersonDiscovery
    {

        [JsonProperty("page")]
        public int pagev { get; set; }

        [JsonProperty("total_results")]
        public int total_results { get; set; }

        [JsonProperty("total_pages")]
        public int total_pages { get; set; }

        [JsonProperty("results")]
        public Person[] results { get; set; }
    }

}
