// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using Newtonsoft.Json;
using System.Collections;
using System.Reflection;
using Microsoft.WindowsAzure.Storage.Table;
//using MovieDBconnection.MovieDiscoveryJsonTypes;

namespace MovieDBconnection.PersonDiscoveryJsonTypes
{
    public class Person : TableEntity
    {
        public Person() { }
        public string popularity { get; set; }
        public string profile_path { get; set; }
        public string name { get; set; }
        public string known_for_department { get; set; }
        public string adult { get; set; }
        public string gender { get; set; }
        public object this[string propertyName]
        {
            set
            {
                PropertyInfo pi = this.GetType().GetProperty(propertyName);
                pi.SetValue(this, value, null);
            }
        }
    }
}
